version: "3"

services:
  universal-consensus:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://user:password@postgres:5432/universal-consensus

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=universal-consensus
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
